plugins {
    id 'java'
    id 'idea'
    id 'org.springframework.boot' version '4.0.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'ru.glebova'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':common')
    implementation 'net.devh:grpc-spring-boot-starter:3.1.0.RELEASE'
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.testcontainers:testcontainers:1.21.4'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter:2.0.3'
    testImplementation 'org.testcontainers:postgresql:1.21.4'
    testImplementation 'org.postgresql:postgresql:42.7.10'
//    testRuntimeOnly 'org.slf4j:slf4j-simple:2.0.17'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'org.liquibase:liquibase-core:4.25.1'
    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.2'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.keycloak:keycloak-admin-client:26.0.8'
    testImplementation 'org.springframework.security:spring-security-test'
    implementation 'org.springframework.kafka:spring-kafka'
    testImplementation 'org.testcontainers:kafka:1.19.7'
}

//configurations {
//    integrationTestImplementation.extendsFrom testImplementation
//    integrationTestRuntimeOnly.extendsFrom testRuntimeOnly
//}


sourceSets {
    integrationTest {
        java.srcDir file('src/integrationTest/java')
        resources.srcDir file('src/integrationTest/resources')
        compileClasspath += sourceSets.main.output + configurations.testRuntimeClasspath
        runtimeClasspath += output + compileClasspath
    }
}

configurations {
    integrationTestImplementation {
        extendsFrom testImplementation
        extendsFrom implementation
    }
    integrationTestRuntimeOnly {
        extendsFrom testRuntimeOnly
        extendsFrom runtimeOnly
    }
}

idea {
    module {
        testSources.from sourceSets.integrationTest.java.srcDirs
        testResources.from sourceSets.integrationTest.resources.srcDirs
    }
}

tasks.register('integrationTest', Test) {
    description = 'Runs integration tests.'
    group = 'verification'
    testClassesDirs = sourceSets.integrationTest.output.classesDirs
    classpath = sourceSets.integrationTest.runtimeClasspath
    useJUnitPlatform()
    shouldRunAfter test
    testLogging {
        events 'passed', 'skipped', 'failed'
    }
}

tasks.named('processIntegrationTestResources') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'skipped', 'failed'
    }
}
