server.port=8081
spring.application.name=storage-service

spring.datasource.url=jdbc:postgresql://localhost:5432/cardealership-storage
spring.datasource.username=admin
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.oauth.clientId=car-dealership-api

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/car-dealership-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/car-dealership-realm/protocol/openid-connect/certs

keycloak.auth-server-url=http://keycloak:8080
keycloak.realm=car-dealership-realm
keycloak.admin.username=admin
keycloak.admin.password=admin
keycloak.admin-client-id=admin-cli

order-service.url=${ORDER_SERVICE_URL:http://localhost:8080}

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all

spring.kafka.consumer.group-id=storage-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.enable-auto-commit=false

spring.kafka.listener.ack-mode=record

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger{36} - %msg%n

grpc.server.port=${GRPC_SERVER_PORT:9090}